server:
  port: 8090

spring:
  application:
    name: msvc-food-court
  datasource:
    url: jdbc:mysql://localhost/foot_court
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
